services:
  application:
    build: .
    container_name: application-container
    depends_on:
      db:
        condition: service_healthy
    environment:
      TELEGRAM_TOKEN:
      TELEGRAM_CHAT_ID:
      LOG_LEVEL: DEBUG
      SERVER_PORT: :9091
      CHECK_INTERVAL: 1m
      CONNECTION_STRING: postgres://postgres:prime666@db:5432/postgres?sslmode=disable
    ports:
      - "9091:9091"

  db:
    image: postgres:18.3-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prime666
      POSTGRES_DB: postgres
    ports:
      - "5442:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5